<?php

/**
 * RelatedPosts Plugin - Show the related posts of the provided post.
 * Copy relatedposts.php to your themedir and style it.
 * 
 *
 * Usage:
 * <code>$theme->related_posts($post);</code>
 *
 */

class recent_posts extends Plugin
{
	private $config= array();
	private $default_options= array (
		'num_post' => '5',
		);

	/**
	 * Required plugin info() implementation provides info to Habari about this plugin.
	 */
	public function info()
	{
		return array(
			'name' => 'Related Posts',
			'url' => '',
			'author' =>'eighty4',
			'authorurl' => 'http://eighty4.se',
			'version' => '0.1',
			'description' => 'Show the related posts based on interception of tags Inspired by Raman Ngs (a.k.a. tinyau) RN Related Posts',
			'license' => 'Apache License 2.0',
		);
	}
	
	public function action_update_check()
	{
	 	Update::add( 'RelatedPosts', '5E5B630C-1276-11DE-AFD8-77AF55D89593', $this->info->version );
	}

	/**
	 * Plugin init action, executed when plugins are initialized.
	 */
	public function action_init()
	{
		$this->class_name= strtolower( get_class( $this ) );
		foreach ( $this->default_options as $name => $unused ) {
			$this->config[$name]= Options::get( $this->class_name . '__' . $name );
		}
		$this->add_template('related_posts', dirname(__FILE__) . '/relatedposts.php');
	}

	/**
	 * Add actions to the plugin page for this plugin
	 * @param array $actions An array of actions that apply to this plugin
	 * @param string $plugin_id The string id of a plugin, generated by the system
	 * @return array The array of actions to attach to the specified $plugin_id
	 **/
	public function filter_plugin_config( $actions, $plugin_id )
	{
		if ( $plugin_id == $this->plugin_id() ) {
			$actions[] = 'Configure';
		}

		return $actions;
	}
	
	/**
	 * Sets the new 'hide_replies' option to '0' to mimic current, non-reply-hiding
	 * functionality.
	 **/
	public function action_plugin_activation( $file )
	{
		if(Plugins::id_from_file($file) == Plugins::id_from_file(__FILE__)) {
			if ( Options::get( 'related_posts__count' ) == null ) {
				Options::set( 'related_posts__count', 5 );
			}
		}
	}

	/**
	 * Respond to the user selecting an action on the plugin page
	 * @param string $plugin_id The string id of the acted-upon plugin
	 * @param string $action The action string supplied via the filter_plugin_config hook
	 **/
	public function action_plugin_ui( $plugin_id, $action )
	{
		if ( $plugin_id == $this->plugin_id() ) {
			switch ( $action ) {
				case 'Configure' :
					$ui = new FormUI( strtolower( get_class( $this ) ) );
					$ui->append( 'text', 'count', 'related_posts__count', 
						_t( 'No. of Post to be shown' ) );
					$ui->append( 'submit', 'save', _t('Save') );
					$ui->out();
					break;
			}
		}
	}

	public function theme_related_posts( $theme, $post = null )
	{	
		// If $post is an array of posts let's hope we want the first one.
		// There's probably a better way of doing this but I'm not positive 
		// that [0] won't be called something else in the future.
		// Go ahead and change this if there's a better solution :)
		//if( $post instanceOf Posts  ) $post = current( $post );	

		// If we don't give it a post use $theme's
		if( $post === null ) $post = $theme->posts;
		
		$theme->related_entry = array();

		if( $post instanceOf Post ) {
			$post_type = Post::type( 'entry' );
			$post_status = Post::status( 'published' );	

			if( is_array( $post->tags ) && $post->tags ) {
				$tags = array_keys( $post->tags );	
				$theme->related_entry = Posts::get( array( 'content_type' => Post::type( 'entry' ),
							'status' => Post::status( 'published' ),
							'limit' => Options::get( 'related_posts__count' ),
							'all:tag' => $tags, // what's the exact difference between all:tag and tag_slug?
							'not:id' => $post->id ) );
			}
		}
		return $theme->fetch( 'related_posts' );
	}
}
?>
